FileVersion = 1
Projects = {TalentShow = {Path = "."}, raylib-beef = "*", rlCImGuiBeef = {Path = "../rlCImGuiBeef"}}
WorkspaceFolders = {Libs = ["corlib", "raylib-beef", "rlCImGuiBeef", "ImGui"]}

[Workspace]
StartupProject = "Leaf"

[Configs.Debug.wasm32]
AllocType = "CRT"
EnableObjectDebugFlags = false
EmitObjectAccessCheck = false
