FileVersion = 1
Dependencies = {corlib = "*", corlib = "*", ImGui = "*", raylib-aseprite-beef = "*", raylib-beef = "*", rlCImGuiBeef = "*", TinySoundFontBeef = "*"}

[Project]
Name = "Leaf"
StartupObject = "Leaf.Program"

[Configs.Debug.Win64]
TargetDirectory = "$(ProjectDir)/dist/$(Platform)_$(Configuration)"
TargetName = "$(ProjectName)_d"
PostBuildCmds = ["CopyFilesIfNewer(\"$(ProjectDir)/res\",\"$(ProjectDir)/dist/$(Platform)_$(Configuration)\")"]

[Configs.Debug.wasm32]
TargetDirectory = "$(ProjectDir)/dist/$(Platform)_$(Configuration)"
TargetName = "leaf"
OtherLinkFlags = "$(LinkFlags) -o index.html --use-preload-plugins -DPLATFORM_WEB --shell-file D:/Software/Beef/wasm/shell.html -s ASYNCIFY=1 -sFORCE_FILESYSTEM"
DebugCommand = ""

[Configs.Debug.Win32]
TargetDirectory = "$(ProjectDir)/dist/$(Platform)_$(Configuration)"
PostBuildCmds = ["CopyFilesIfNewer(\"$(ProjectDir)/res\",\"$(ProjectDir)/dist/$(Platform)_$(Configuration)\")"]

[Configs.Release.wasm32]
OtherLinkFlags = "$(LinkFlags) -o index.html -Wall -std=c99 -D_DEFAULT_SOURCE --use-preload-plugins --preload-file res -Wno-missing-braces -Wunused-result -Os -I. -I C:/raylib/raylib/src -I C:/raylib/raylib/src/external -L. -L C:/raylib/raylib/src -s USE_GLFW=3 -s TOTAL_MEMORY=67108864 -s FORCE_FILESYSTEM=1 --shell-file D:/Software/Beef/wasm/shell.html C:/raylib/raylib/src/web/libraylib.a -DPLATFORM_WEB -s EXPORTED_FUNCTIONS=['_free','_malloc','_main'] -s EXPORTED_RUNTIME_METHODS=ccall"

[Configs.Release.Win64]
TargetDirectory = "$(ProjectDir)/dist/$(Platform)_$(Configuration)"
PostBuildCmds = ["CopyFilesIfNewer(\"$(ProjectDir)/res\",\"$(ProjectDir)/dist/$(Platform)_$(Configuration)\")"]

[Configs.Paranoid.Win64]
TargetDirectory = "$(ProjectDir)/dist/$(Platform)_$(Configuration)"
PostBuildCmds = ["CopyFilesIfNewer(\"$(ProjectDir)/res\",\"$(ProjectDir)/dist/$(Platform)_$(Configuration)\")"]

[Configs.Test.Win64]
TargetDirectory = "$(ProjectDir)/dist/$(Platform)_$(Configuration)"
PostBuildCmds = ["CopyFilesIfNewer(\"$(ProjectDir)/res\",\"$(ProjectDir)/dist/$(Platform)_$(Configuration)\")"]

[[ProjectFolder.Items]]
Type = "IgnoreSource"
Name = "Tweenie.bf"

[[ProjectFolder.Items]]
Type = "AutoFolder"
Name = "Audio"

[[ProjectFolder.Items.Items]]
Type = "IgnoreSource"
Name = "MidiReader.bf"

[[ProjectFolder.Items]]
Type = "AutoFolder"
Name = "Scenes"

[[ProjectFolder.Items.Items]]
Type = "IgnoreSource"
Name = "SceneNetworking - Copy.bf"
