FileVersion = 1
Projects = {Leaf = {Path = "."}, raylib-beef = "*", ImGui = "*", rlCImGuiBeef = "*", BJSON = "*", raylib-aseprite-beef = "*"}
Unlocked = ["rlCImGuiBeef", "raylib-aseprite-beef"]
WorkspaceFolders = {Libs = ["corlib", "raylib-beef", "ImGui", "rlCImGuiBeef", "BJSON", "raylib-aseprite-beef"]}

[Workspace]
StartupProject = "Leaf"

[Configs.Debug.wasm32]
AllocType = "CRT"
EnableObjectDebugFlags = false
EmitObjectAccessCheck = false
