FileVersion = 1
Projects = {TalentShow = {Path = "."}, raylib-beef = "*", ImGui = "*", rlCImGuiBeef = "*", BJSON = "*"}
Unlocked = ["rlCImGuiBeef"]
WorkspaceFolders = {Libs = ["corlib", "raylib-beef", "ImGui", "rlCImGuiBeef", "BJSON"]}

[Workspace]
StartupProject = "Leaf"

[Configs.Debug.wasm32]
AllocType = "CRT"
EnableObjectDebugFlags = false
EmitObjectAccessCheck = false
