FileVersion = 1
Projects = {Leaf = {Path = "."}, raylib-beef = "*", ImGui = "*", rlCImGuiBeef = "*", BJSON = "*", raylib-aseprite-beef = "*", TinySoundFontBeef = {Path = "../../../Software/Beef/BeefLibs/TinySoundFontBeef"}}
Unlocked = ["rlCImGuiBeef", "raylib-aseprite-beef", "corlib"]
WorkspaceFolders = {Libs = ["corlib", "raylib-beef", "ImGui", "rlCImGuiBeef", "BJSON", "raylib-aseprite-beef", "TinySoundFontBeef"]}

[Workspace]
StartupProject = "Leaf"

[Configs.Debug.wasm32]
AllocType = "CRT"
EnableObjectDebugFlags = false
EmitObjectAccessCheck = false
