FileVersion = 1
LastConfig = "Debug"
LastPlatform = "Win64"
RecentFilesList = ["src\\Scenes\\SceneInverseKinematic.bf", "src\\Scenes\\SceneTextMesh.bf", "Disassembly", "src\\Asset\\AssetLoader.bf", "src\\Audio\\MidiReaderOld.bf", "src\\Game.bf"]

[MainWindow]
X = 742
Y = 0
Width = 1178
Height = 884
ShowKind = "ShowMaximized"

[MainDockingFrame]
Type = "DockingFrame"
SplitType = 2

[[MainDockingFrame.DockedWidgets]]
RequestedWidth = 350.0
RequestedHeight = 834.0
SizePriority = 834.0
Type = "DockingFrame"
SplitType = 1

[[MainDockingFrame.DockedWidgets.DockedWidgets]]
RequestedWidth = 275.0
RequestedHeight = 200.0
Type = "TabbedView"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
Active = true
TabLabel = "Workspace"
TabWidth = 111.7023
TabIsPinned = false
Type = "ProjectPanel"

[[MainDockingFrame.DockedWidgets.DockedWidgets]]
IsFillWidget = true
Permanent = true
RequestedWidth = 1375.24
RequestedHeight = 695.76
SizePriority = 1375.24
DefaultDocumentsTabbedView = true
Type = "TabbedView"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
Active = true
TabLabel = "SceneInverseKinematic.bf"
TabWidth = 172.5536
TabIsPinned = false
Type = "SourceViewPanel"
FilePath = "src\\Scenes\\SceneInverseKinematic.bf"
CursorPos = 788
VertPos = 272.0404
ProjectName = "Leaf"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "SceneTextMesh.bf"
TabWidth = 140.4259
TabIsPinned = false
Type = "SourceViewPanel"
FilePath = "src\\Scenes\\SceneTextMesh.bf"
CursorPos = 190
VertPos = 855.0
ProjectName = "Leaf"

[[MainDockingFrame.DockedWidgets.DockedWidgets]]
RequestedWidth = 266.0
RequestedHeight = 194.0
Type = "TabbedView"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
Active = true
TabLabel = "Autocomplete"
TabWidth = 129.7874
TabIsPinned = false
Type = "AutoCompletePanel"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Call Stack"
TabWidth = 103.1916
TabIsPinned = false
Type = "CallStackPanel"

[[MainDockingFrame.DockedWidgets]]
RequestedWidth = 250.0
RequestedHeight = 151.0
Type = "TabbedView"

[[MainDockingFrame.DockedWidgets.Tabs]]
Active = true
TabLabel = "Output"
TabWidth = 90.42564
TabIsPinned = false
Type = "OutputPanel"

[[MainDockingFrame.DockedWidgets.Tabs]]
TabLabel = "Immediate"
TabWidth = 108.5108
TabIsPinned = false
Type = "ImmediatePanel"

[[MainDockingFrame.DockedWidgets.Tabs]]
TabLabel = "Memory"
TabWidth = 96.80864
TabIsPinned = false
Type = "MemoryPanel"
AutoResize = "Auto_Mul8"
RequestedWidth = 300.0

[[MainDockingFrame.DockedWidgets.Tabs]]
TabLabel = "Watch"
TabWidth = 86.17031
TabIsPinned = false
Type = "WatchPanel"
Columns = [{Width = 200.0}, {Width = 200.0}, {Width = 200.0}]

[[MainDockingFrame.DockedWidgets.Tabs.Items]]
EvalStr = "Enumerator"

[[MainDockingFrame.DockedWidgets.Tabs.Items]]
EvalStr = "Enumerator"

[[MainDockingFrame.DockedWidgets.Tabs.Items]]
EvalStr = "IsEnumeratorReady"

[[MainDockingFrame.DockedWidgets.Tabs.Items]]
EvalStr = "offset"

[[MainDockingFrame.DockedWidgets.Tabs.Items]]
EvalStr = "Camera"

[[MainDockingFrame.DockedWidgets.Tabs.Items]]
EvalStr = "Camera.zoom"

[[MainDockingFrame.DockedWidgets.Tabs.Items]]
EvalStr = "Camera"

[[MainDockingFrame.DockedWidgets.Tabs.Items]]
EvalStr = ""

[[MainDockingFrame.DockedWidgets.Tabs]]
TabLabel = "Auto Watches"
TabWidth = 128.7236
TabIsPinned = false
Type = "AutoWatchPanel"
Columns = [{Width = 200.0}, {Width = 200.0}, {Width = 200.0}]

[[MainDockingFrame.DockedWidgets.Tabs]]
TabLabel = "Find Results"
TabWidth = 117.0215
TabIsPinned = false
Type = "FindResultsPanel"

[[MainDockingFrame.DockedWidgets.Tabs]]
TabLabel = "Console"
TabWidth = 94.68098
TabIsPinned = false
Type = "ConsolePanel"

[[BookmarkFolders]]
Title = ""

[OutputFilters]
ModuleLoadMessages = false
ModuleUnloadMessages = false
ProcessExitMessages = false
ThreadCreateMessages = false
ThreadExitMessages = false
SymbolLoadMessages = false
ProgramOutput = false
