FileVersion = 1
Projects = {Leaf = {Path = "."}, raylib-beef = "*", ImGui = "*", rlCImGuiBeef = "*", raylib-aseprite-beef = "*", TinySoundFontBeef = {Path = "../../../Software/Beef/BeefLibs/TinySoundFontBeef"}, Jolt = {Path = "../../../Software/Beef/BeefLibs/C2Beef-Binding-Generator/Jolt"}}
Unlocked = ["rlCImGuiBeef", "raylib-aseprite-beef", "corlib", "BJSON"]
WorkspaceFolders = {Libs = ["corlib", "raylib-beef", "ImGui", "rlCImGuiBeef", "raylib-aseprite-beef", "TinySoundFontBeef", "BJSON", "Jolt"]}

[Workspace]
StartupProject = "Leaf"

[[Workspace.DistinctOptions]]
Filter = ""

[Configs.Debug.wasm32]
AllocType = "CRT"
EnableObjectDebugFlags = false
EmitObjectAccessCheck = false
