FileVersion = 1
LastConfig = "Debug"
LastPlatform = "Win64"
RecentFilesList = ["src\\Program.bf", "src\\Game.bf", "Disassembly", "Disassembly"]

[MainWindow]
X = 373
Y = 0
Width = 1178
Height = 884
ShowKind = "ShowMaximized"

[MainDockingFrame]
Type = "DockingFrame"
SplitType = 2

[[MainDockingFrame.DockedWidgets]]
RequestedWidth = 350.0
RequestedHeight = 834.0
SizePriority = 834.0
Type = "DockingFrame"
SplitType = 1

[[MainDockingFrame.DockedWidgets.DockedWidgets]]
RequestedWidth = 275.0
RequestedHeight = 200.0
Type = "TabbedView"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
Active = true
TabLabel = "Workspace"
TabWidth = 109.8215
TabIsPinned = false
Type = "ProjectPanel"

[[MainDockingFrame.DockedWidgets.DockedWidgets]]
IsFillWidget = true
Permanent = true
RequestedWidth = 1667.0
RequestedHeight = 695.76
SizePriority = 1667.0
DefaultDocumentsTabbedView = true
Type = "TabbedView"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
Active = true
TabLabel = "Program.bf"
TabWidth = 90.71439
TabIsPinned = false
Type = "SourceViewPanel"
FilePath = "src\\Program.bf"
ProjectName = "Leaf"

[[MainDockingFrame.DockedWidgets.DockedWidgets]]
RequestedWidth = 266.0
RequestedHeight = 194.0
Type = "TabbedView"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Autocomplete"
TabWidth = 126.7859
TabIsPinned = false
Type = "AutoCompletePanel"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
Active = true
TabLabel = "Call Stack"
TabWidth = 101.7858
TabIsPinned = false
Type = "CallStackPanel"

[[MainDockingFrame.DockedWidgets]]
RequestedWidth = 250.0
RequestedHeight = 173.0
Type = "TabbedView"

[[MainDockingFrame.DockedWidgets.Tabs]]
Active = true
TabLabel = "Output"
TabWidth = 90.17864
TabIsPinned = false
Type = "OutputPanel"

[[MainDockingFrame.DockedWidgets.Tabs]]
TabLabel = "Errors"
TabWidth = 82.14291
TabIsPinned = false
Type = "ErrorsPanel"

[[MainDockingFrame.DockedWidgets.Tabs]]
TabLabel = "Modules"
TabWidth = 97.32152
TabIsPinned = false
Type = "ModulePanel"

[[MainDockingFrame.DockedWidgets.Tabs]]
TabLabel = "Threads"
TabWidth = 92.85722
TabIsPinned = false
Type = "ThreadPanel"

[[MainDockingFrame.DockedWidgets.Tabs]]
TabLabel = "Profile"
TabWidth = 83.92863
TabIsPinned = false
Type = "ProfilePanel"

[[MainDockingFrame.DockedWidgets.Tabs]]
TabLabel = "Bookmarks"
TabWidth = 110.7144
TabIsPinned = false
Type = "BookmarksPanel"

[[MainDockingFrame.DockedWidgets.Tabs]]
TabLabel = "Breakpoints"
TabWidth = 114.2858
TabIsPinned = false
Type = "BreakpointPanel"

[[MainDockingFrame.DockedWidgets.Tabs]]
TabLabel = "Find Results"
TabWidth = 115.1787
TabIsPinned = false
Type = "FindResultsPanel"

[[MainDockingFrame.DockedWidgets.Tabs]]
TabLabel = "Immediate"
TabWidth = 108.0358
TabIsPinned = false
Type = "ImmediatePanel"

[[MainDockingFrame.DockedWidgets.Tabs]]
TabLabel = "Memory"
TabWidth = 96.42866
TabIsPinned = false
Type = "MemoryPanel"
AutoResize = "Auto_Mul8"
RequestedWidth = 300.0

[[MainDockingFrame.DockedWidgets.Tabs]]
TabLabel = "Watch"
TabWidth = 84.8215
TabIsPinned = false
Type = "WatchPanel"
Columns = [{Width = 200.0}, {Width = 200.0}, {Width = 200.0}]
Items = ["Enumerator", "Enumerator", "IsEnumeratorReady", ""]

[[MainDockingFrame.DockedWidgets.Tabs]]
TabLabel = "Auto Watches"
TabWidth = 126.7859
TabIsPinned = false
Type = "AutoWatchPanel"
Columns = [{Width = 200.0}, {Width = 200.0}, {Width = 200.0}]

[[BookmarkFolders]]
Title = ""

[OutputFilters]
ModuleLoadMessages = false
ModuleUnloadMessages = false
ProcessExitMessages = false
ThreadCreateMessages = false
ThreadExitMessages = false
SymbolLoadMessages = false
ProgramOutput = false
