FileVersion = 1
LastConfig = "Debug"
LastPlatform = "Win64"
RecentFilesList = ["src\\Scenes\\SceneTextMesh.bf", "src\\Text\\RichText.bf", "src\\Text\\TextSprite.bf", "Disassembly", "d:\\Software\\Beef\\BeefLibs\\corlib\\src\\Math.bf", "d:\\Software\\Beef\\BeefLibs\\corlib\\src\\Int32.bf", "Disassembly", "src\\Audio\\MidiReaderOld.bf", "src\\Game.bf"]

[MainWindow]
X = 1276
Y = 0
Width = 644
Height = 884
ShowKind = "ShowMaximized"

[MainDockingFrame]
Type = "DockingFrame"
SplitType = 2

[[MainDockingFrame.DockedWidgets]]
RequestedWidth = 350.0
RequestedHeight = 834.0
SizePriority = 834.0
Type = "DockingFrame"
SplitType = 1

[[MainDockingFrame.DockedWidgets.DockedWidgets]]
RequestedWidth = 247.0
RequestedHeight = 200.0
Type = "TabbedView"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
Active = true
TabLabel = "Workspace"
TabWidth = 111.7023
TabIsPinned = false
Type = "ProjectPanel"

[[MainDockingFrame.DockedWidgets.DockedWidgets]]
IsFillWidget = true
Permanent = true
RequestedWidth = 1286.24
RequestedHeight = 695.76
SizePriority = 1286.24
DefaultDocumentsTabbedView = true
Type = "TabbedView"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
Active = true
TabLabel = "SceneTextMesh.bf"
TabWidth = 131.0641
TabIsPinned = false
Type = "SourceViewPanel"
FilePath = "src\\Scenes\\SceneTextMesh.bf"
CursorPos = 878
VertPos = 1235.0
ProjectName = "Leaf"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "RichText.bf"
TabWidth = 91.70229
TabIsPinned = false
Type = "SourceViewPanel"
FilePath = "src\\Text\\RichText.bf"
CursorPos = 1839
VertPos = 1520.0
ProjectName = "Leaf"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "TextSprite.bf"
TabWidth = 99.14912
TabIsPinned = false
Type = "SourceViewPanel"
FilePath = "src\\Text\\TextSprite.bf"
CursorPos = 221
ProjectName = "Leaf"

[[MainDockingFrame.DockedWidgets.DockedWidgets]]
RequestedWidth = 363.0
RequestedHeight = 194.0
Type = "TabbedView"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Autocomplete"
TabWidth = 129.7874
TabIsPinned = false
Type = "AutoCompletePanel"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
Active = true
TabLabel = "Call Stack"
TabWidth = 103.1916
TabIsPinned = false
Type = "CallStackPanel"

[[MainDockingFrame.DockedWidgets]]
RequestedWidth = 250.0
RequestedHeight = 187.0
Type = "TabbedView"

[[MainDockingFrame.DockedWidgets.Tabs]]
Active = true
TabLabel = "Output"
TabWidth = 90.42564
TabIsPinned = false
Type = "OutputPanel"

[[MainDockingFrame.DockedWidgets.Tabs]]
TabLabel = "Immediate"
TabWidth = 108.5108
TabIsPinned = false
Type = "ImmediatePanel"

[[MainDockingFrame.DockedWidgets.Tabs]]
TabLabel = "Memory"
TabWidth = 96.80864
TabIsPinned = false
Type = "MemoryPanel"
AutoResize = "Auto_Mul8"
RequestedWidth = 300.0

[[MainDockingFrame.DockedWidgets.Tabs]]
TabLabel = "Watch"
TabWidth = 86.17031
TabIsPinned = false
Type = "WatchPanel"
Columns = [{Width = 160.0}, {Width = 388.0}, {Width = 160.0}]

[[MainDockingFrame.DockedWidgets.Tabs.Items]]
EvalStr = "sock"

[[MainDockingFrame.DockedWidgets.Tabs.Items]]
EvalStr = ""

[[MainDockingFrame.DockedWidgets.Tabs]]
TabLabel = "Auto Watches"
TabWidth = 128.7236
TabIsPinned = false
Type = "AutoWatchPanel"
Columns = [{Width = 160.0}, {Width = 160.0}, {Width = 160.0}]

[[MainDockingFrame.DockedWidgets.Tabs]]
TabLabel = "Find Results"
TabWidth = 117.0215
TabIsPinned = false
Type = "FindResultsPanel"

[[Breakpoints]]
File = "src\\SceneNetworking.bf"
Line = 30
Column = 2

[[BookmarkFolders]]
Title = ""

[OutputFilters]
ModuleLoadMessages = false
ModuleUnloadMessages = false
ProcessExitMessages = false
ThreadCreateMessages = false
ThreadExitMessages = false
SymbolLoadMessages = false
ProgramOutput = false
