FileVersion = 1
LastConfig = "Debug"
LastPlatform = "Win64"
RecentFilesList = ["src\\Program.bf", "Disassembly", "Disassembly", "Disassembly", "d:\\Software\\Beef\\BeefLibs\\corlib\\src\\Math.bf", "d:\\Software\\Beef\\BeefLibs\\corlib\\src\\Int32.bf", "Disassembly", "src\\Audio\\MidiReaderOld.bf", "src\\Game.bf"]

[MainWindow]
X = 425
Y = 11
Width = 644
Height = 884
ShowKind = "ShowMaximized"

[MainDockingFrame]
Type = "DockingFrame"
SplitType = 2

[[MainDockingFrame.DockedWidgets]]
RequestedWidth = 350.0
RequestedHeight = 834.0
SizePriority = 834.0
Type = "DockingFrame"
SplitType = 1

[[MainDockingFrame.DockedWidgets.DockedWidgets]]
RequestedWidth = 247.0
RequestedHeight = 200.0
Type = "TabbedView"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
Active = true
TabLabel = "Workspace"
TabWidth = 110.9091
TabIsPinned = false
Type = "ProjectPanel"

[[MainDockingFrame.DockedWidgets.DockedWidgets]]
IsFillWidget = true
Permanent = true
RequestedWidth = 1286.24
RequestedHeight = 695.76
SizePriority = 1286.24
DefaultDocumentsTabbedView = true
Type = "TabbedView"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
Active = true
TabLabel = "Program.bf"
TabWidth = 91.81818
TabIsPinned = false
Type = "SourceViewPanel"
FilePath = "src\\Program.bf"
CursorPos = 166
ProjectName = "Leaf"

[[MainDockingFrame.DockedWidgets.DockedWidgets]]
RequestedWidth = 363.0
RequestedHeight = 194.0
Type = "TabbedView"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Autocomplete"
TabWidth = 128.1818
TabIsPinned = false
Type = "AutoCompletePanel"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
Active = true
TabLabel = "Call Stack"
TabWidth = 102.7273
TabIsPinned = false
Type = "CallStackPanel"

[[MainDockingFrame.DockedWidgets]]
RequestedWidth = 250.0
RequestedHeight = 397.0
Type = "TabbedView"

[[MainDockingFrame.DockedWidgets.Tabs]]
Active = true
TabLabel = "Output"
TabWidth = 90.90909
TabIsPinned = false
Type = "OutputPanel"

[[MainDockingFrame.DockedWidgets.Tabs]]
TabLabel = "Immediate"
TabWidth = 109.0909
TabIsPinned = false
Type = "ImmediatePanel"

[[MainDockingFrame.DockedWidgets.Tabs]]
TabLabel = "Watch"
TabWidth = 85.45454
TabIsPinned = false
Type = "WatchPanel"
Columns = [{Width = 187.0}, {Width = 454.0}, {Width = 187.0}]

[[MainDockingFrame.DockedWidgets.Tabs.Items]]
EvalStr = "sock"

[[MainDockingFrame.DockedWidgets.Tabs.Items]]
EvalStr = ""

[[MainDockingFrame.DockedWidgets.Tabs]]
TabLabel = "Auto Watches"
TabWidth = 128.1818
TabIsPinned = false
Type = "AutoWatchPanel"
Columns = [{Width = 187.0}, {Width = 187.0}, {Width = 187.0}]

[[MainDockingFrame.DockedWidgets.Tabs]]
TabLabel = "Find Results"
TabWidth = 116.3636
TabIsPinned = false
Type = "FindResultsPanel"

[[MainDockingFrame.DockedWidgets.Tabs]]
TabLabel = "Errors"
TabWidth = 82.72727
TabIsPinned = false
Type = "ErrorsPanel"

[[Breakpoints]]
File = "src\\SceneNetworking.bf"
Line = 30
Column = 2

[[BookmarkFolders]]
Title = ""

[OutputFilters]
ModuleLoadMessages = false
ModuleUnloadMessages = false
ProcessExitMessages = false
ThreadCreateMessages = false
ThreadExitMessages = false
SymbolLoadMessages = false
ProgramOutput = false
