FileVersion = 1
LastConfig = "Debug"
LastPlatform = "Win64"
RecentFilesList = ["src\\Scenes\\SceneOrderedDrawCall.bf", "src\\Program.bf", "TODO.txt", "src\\Game.bf", "Disassembly", "Disassembly"]

[MainWindow]
X = 2438
Y = 0
Width = 1178
Height = 884
ShowKind = "ShowMaximized"

[MainDockingFrame]
Type = "DockingFrame"
SplitType = 2

[[MainDockingFrame.DockedWidgets]]
RequestedWidth = 350.0
RequestedHeight = 834.0
SizePriority = 834.0
Type = "DockingFrame"
SplitType = 1

[[MainDockingFrame.DockedWidgets.DockedWidgets]]
RequestedWidth = 275.0
RequestedHeight = 200.0
Type = "TabbedView"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
Active = true
TabLabel = "Workspace"
TabWidth = 110.4168
TabIsPinned = false
Type = "ProjectPanel"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "TODO.txt"
TabWidth = 81.0418
TabIsPinned = false
Type = "SourceViewPanel"
FilePath = "TODO.txt"

[[MainDockingFrame.DockedWidgets.DockedWidgets]]
IsFillWidget = true
Permanent = true
RequestedWidth = 1667.0
RequestedHeight = 695.76
SizePriority = 1667.0
DefaultDocumentsTabbedView = true
Type = "TabbedView"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Program.bf"
TabWidth = 91.4585
TabIsPinned = false
Type = "SourceViewPanel"
FilePath = "src\\Program.bf"
CursorPos = 307
ProjectName = "Leaf"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
Active = true
TabLabel = "SceneOrderedDrawCall.bf"
TabWidth = 169.5837
TabIsPinned = false
Type = "SourceViewPanel"
FilePath = "src\\Scenes\\SceneOrderedDrawCall.bf"
CursorPos = 497
VertPos = 380.0
ProjectName = "Leaf"

[[MainDockingFrame.DockedWidgets.DockedWidgets]]
RequestedWidth = 266.0
RequestedHeight = 194.0
Type = "TabbedView"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
Active = true
TabLabel = "Autocomplete"
TabWidth = 128.1252
TabIsPinned = false
Type = "AutoCompletePanel"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Call Stack"
TabWidth = 102.0835
TabIsPinned = false
Type = "CallStackPanel"

[[MainDockingFrame.DockedWidgets]]
RequestedWidth = 250.0
RequestedHeight = 222.0
Type = "TabbedView"

[[MainDockingFrame.DockedWidgets.Tabs]]
TabLabel = "Output"
TabWidth = 89.58344
TabIsPinned = false
Type = "OutputPanel"

[[MainDockingFrame.DockedWidgets.Tabs]]
TabLabel = "Immediate"
TabWidth = 107.2918
TabIsPinned = false
Type = "ImmediatePanel"

[[MainDockingFrame.DockedWidgets.Tabs]]
TabLabel = "Memory"
TabWidth = 95.83346
TabIsPinned = false
Type = "MemoryPanel"
AutoResize = "Auto_Mul8"
RequestedWidth = 300.0

[[MainDockingFrame.DockedWidgets.Tabs]]
TabLabel = "Watch"
TabWidth = 85.41676
TabIsPinned = false
Type = "WatchPanel"
Columns = [{Width = 200.0}, {Width = 200.0}, {Width = 200.0}]
Items = ["Enumerator", "Enumerator", "IsEnumeratorReady", ""]

[[MainDockingFrame.DockedWidgets.Tabs]]
TabLabel = "Auto Watches"
TabWidth = 127.0835
TabIsPinned = false
Type = "AutoWatchPanel"
Columns = [{Width = 200.0}, {Width = 200.0}, {Width = 200.0}]

[[MainDockingFrame.DockedWidgets.Tabs]]
TabLabel = "Find Results"
TabWidth = 115.6252
TabIsPinned = false
Type = "FindResultsPanel"

[[MainDockingFrame.DockedWidgets.Tabs]]
Active = true
TabLabel = "Console"
TabWidth = 93.75012
TabIsPinned = false
Type = "ConsolePanel"

[[BookmarkFolders]]
Title = ""

[OutputFilters]
ModuleLoadMessages = false
ModuleUnloadMessages = false
ProcessExitMessages = false
ThreadCreateMessages = false
ThreadExitMessages = false
SymbolLoadMessages = false
ProgramOutput = false
