FileVersion = 1
LastConfig = "Debug"
LastPlatform = "wasm32"
RecentFilesList = ["src\\Program.bf", "src\\GameEngine.bf", "src\\Extensions\\ExtVector2.bf", "src\\Game.bf", "d:\\Software\\Beef\\BeefLibs\\corlib\\src\\Diagnostics\\Stopwatch.bf", "Disassembly", "Disassembly"]

[MainWindow]
X = 248
Y = 0
Width = 1178
Height = 884
ShowKind = "ShowMaximized"

[MainDockingFrame]
Type = "DockingFrame"
SplitType = 2

[[MainDockingFrame.DockedWidgets]]
RequestedWidth = 350.0
RequestedHeight = 834.0
SizePriority = 834.0
Type = "DockingFrame"
SplitType = 1

[[MainDockingFrame.DockedWidgets.DockedWidgets]]
RequestedWidth = 265.0
RequestedHeight = 200.0
Type = "DockingFrame"
SplitType = 2

[[MainDockingFrame.DockedWidgets.DockedWidgets.DockedWidgets]]
RequestedWidth = 250.0
RequestedHeight = 200.0
SizePriority = 0.7871674
Type = "TabbedView"

[[MainDockingFrame.DockedWidgets.DockedWidgets.DockedWidgets.Tabs]]
Active = true
TabLabel = "Workspace"
TabWidth = 110.2273
TabIsPinned = false
Type = "ProjectPanel"

[[MainDockingFrame.DockedWidgets.DockedWidgets.DockedWidgets]]
RequestedWidth = 1918.0
RequestedHeight = 207.0
SizePriority = 0.2128326
Type = "TabbedView"

[[MainDockingFrame.DockedWidgets.DockedWidgets.DockedWidgets.Tabs]]
Active = true
TabLabel = "Autocomplete"
TabWidth = 127.2727
TabIsPinned = false
Type = "AutoCompletePanel"

[[MainDockingFrame.DockedWidgets.DockedWidgets]]
IsFillWidget = true
Permanent = true
RequestedWidth = 1667.0
RequestedHeight = 150.0
SizePriority = 1667.0
DefaultDocumentsTabbedView = true
Type = "TabbedView"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "GameEngine.bf"
TabWidth = 112.9546
TabIsPinned = false
Type = "SourceViewPanel"
FilePath = "src\\GameEngine.bf"
CursorPos = 1524
VertPos = 864.0
ProjectName = "Leaf"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "ExtVector2.bf"
TabWidth = 102.7273
TabIsPinned = false
Type = "SourceViewPanel"
FilePath = "src\\Extensions\\ExtVector2.bf"
ProjectName = "Leaf"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
Active = true
TabLabel = "Program.bf"
TabWidth = 89.09093
TabIsPinned = false
Type = "SourceViewPanel"
FilePath = "src\\Program.bf"
CursorPos = 435
VertPos = 124.76
ProjectName = "Leaf"

[[MainDockingFrame.DockedWidgets]]
RequestedWidth = 250.0
RequestedHeight = 302.0
Type = "TabbedView"

[[MainDockingFrame.DockedWidgets.Tabs]]
Active = true
TabLabel = "Output"
TabWidth = 88.63637
TabIsPinned = false
Type = "OutputPanel"

[[MainDockingFrame.DockedWidgets.Tabs]]
TabLabel = "Call Stack"
TabWidth = 104.5455
TabIsPinned = false
Type = "CallStackPanel"

[[MainDockingFrame.DockedWidgets.Tabs]]
TabLabel = "Errors"
TabWidth = 82.95455
TabIsPinned = false
Type = "ErrorsPanel"

[[MainDockingFrame.DockedWidgets.Tabs]]
TabLabel = "Modules"
TabWidth = 97.72728
TabIsPinned = false
Type = "ModulePanel"

[[MainDockingFrame.DockedWidgets.Tabs]]
TabLabel = "Threads"
TabWidth = 94.31819
TabIsPinned = false
Type = "ThreadPanel"

[[MainDockingFrame.DockedWidgets.Tabs]]
TabLabel = "Profile"
TabWidth = 85.22728
TabIsPinned = false
Type = "ProfilePanel"

[[MainDockingFrame.DockedWidgets.Tabs]]
TabLabel = "Bookmarks"
TabWidth = 109.0909
TabIsPinned = false
Type = "BookmarksPanel"

[[MainDockingFrame.DockedWidgets.Tabs]]
TabLabel = "Breakpoints"
TabWidth = 114.7727
TabIsPinned = false
Type = "BreakpointPanel"

[[MainDockingFrame.DockedWidgets.Tabs]]
TabLabel = "Find Results"
TabWidth = 117.0455
TabIsPinned = false
Type = "FindResultsPanel"

[[MainDockingFrame.DockedWidgets.Tabs]]
TabLabel = "Immediate"
TabWidth = 109.0909
TabIsPinned = false
Type = "ImmediatePanel"

[[MainDockingFrame.DockedWidgets.Tabs]]
TabLabel = "Memory"
TabWidth = 95.45455
TabIsPinned = false
Type = "MemoryPanel"
AutoResize = "Auto_Mul8"
RequestedWidth = 300.0

[[MainDockingFrame.DockedWidgets.Tabs]]
TabLabel = "Watch"
TabWidth = 85.22728
TabIsPinned = false
Type = "WatchPanel"
Columns = [{Width = 200.0}, {Width = 200.0}, {Width = 200.0}]
Items = [""]

[[MainDockingFrame.DockedWidgets.Tabs]]
TabLabel = "Auto Watches"
TabWidth = 127.2727
TabIsPinned = false
Type = "AutoWatchPanel"
Columns = [{Width = 200.0}, {Width = 200.0}, {Width = 200.0}]

[[BookmarkFolders]]
Title = ""

[OutputFilters]
ModuleLoadMessages = false
ModuleUnloadMessages = false
ProcessExitMessages = false
ThreadCreateMessages = false
ThreadExitMessages = false
SymbolLoadMessages = false
ProgramOutput = false
