FileVersion = 1
LastConfig = "Debug"
LastPlatform = "Win64"
RecentFilesList = ["src\\SceneNetworking.bf", "src\\Engine\\GameEngine.bf", "src\\Scenes\\SceneDefault.bf", "src\\Program.bf", "d:\\Software\\Beef\\BeefLibs\\corlib\\src\\Bitfield.bf", "d:\\Software\\Beef\\BeefLibs\\BJSON\\BJSON\\src\\Models\\JsonValue.bf", "Disassembly", "d:\\Software\\Beef\\BeefLibs\\corlib\\src\\Math.bf", "d:\\Software\\Beef\\BeefLibs\\corlib\\src\\Int32.bf", "Disassembly", "src\\Audio\\MidiReaderOld.bf", "src\\Game.bf"]

[MainWindow]
X = 742
Y = 0
Width = 1178
Height = 884
ShowKind = "ShowMaximized"

[MainDockingFrame]
Type = "DockingFrame"
SplitType = 2

[[MainDockingFrame.DockedWidgets]]
RequestedWidth = 350.0
RequestedHeight = 834.0
SizePriority = 834.0
Type = "DockingFrame"
SplitType = 1

[[MainDockingFrame.DockedWidgets.DockedWidgets]]
RequestedWidth = 247.0
RequestedHeight = 200.0
Type = "TabbedView"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
Active = true
TabLabel = "Workspace"
TabWidth = 111.7023
TabIsPinned = false
Type = "ProjectPanel"

[[MainDockingFrame.DockedWidgets.DockedWidgets]]
IsFillWidget = true
Permanent = true
RequestedWidth = 1286.24
RequestedHeight = 695.76
SizePriority = 1286.24
DefaultDocumentsTabbedView = true
Type = "TabbedView"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Program.bf"
TabWidth = 92.76612
TabIsPinned = false
Type = "SourceViewPanel"
FilePath = "src\\Program.bf"
CursorPos = 306
ProjectName = "Leaf"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "JsonValue.bf"
TabWidth = 100.213
TabIsPinned = false
Type = "SourceViewPanel"
FilePath = "d:\\Software\\Beef\\BeefLibs\\BJSON\\BJSON\\src\\Models\\JsonValue.bf"
CursorPos = 8259
ProjectName = "BJSON"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Bitfield.bf"
TabWidth = 84.25546
TabIsPinned = false
Type = "SourceViewPanel"
FilePath = "d:\\Software\\Beef\\BeefLibs\\corlib\\src\\Bitfield.bf"
CursorPos = 5288
VertPos = 3572.0
ProjectName = "corlib"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
Active = true
TabLabel = "SceneNetworking.bf"
TabWidth = 153.1919
TabIsPinned = false
Type = "SourceViewPanel"
FilePath = "src\\SceneNetworking.bf"
CursorPos = 285
VertPos = 95.0
ProjectName = "Leaf"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "SceneDefault.bf"
TabWidth = 127.6599
TabIsPinned = false
Type = "SourceViewPanel"
FilePath = "src\\Scenes\\SceneDefault.bf"
CursorPos = 316
ProjectName = "Leaf"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "GameEngine.bf"
TabWidth = 124.4684
TabIsPinned = false
Type = "SourceViewPanel"
FilePath = "src\\Engine\\GameEngine.bf"
CursorPos = 3225
VertPos = 2432.0
ProjectName = "Leaf"

[[MainDockingFrame.DockedWidgets.DockedWidgets]]
RequestedWidth = 363.0
RequestedHeight = 194.0
Type = "TabbedView"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Autocomplete"
TabWidth = 129.7874
TabIsPinned = false
Type = "AutoCompletePanel"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
Active = true
TabLabel = "Call Stack"
TabWidth = 103.1916
TabIsPinned = false
Type = "CallStackPanel"

[[MainDockingFrame.DockedWidgets]]
RequestedWidth = 250.0
RequestedHeight = 206.0
Type = "TabbedView"

[[MainDockingFrame.DockedWidgets.Tabs]]
Active = true
TabLabel = "Output"
TabWidth = 90.42564
TabIsPinned = false
Type = "OutputPanel"

[[MainDockingFrame.DockedWidgets.Tabs]]
TabLabel = "Immediate"
TabWidth = 108.5108
TabIsPinned = false
Type = "ImmediatePanel"

[[MainDockingFrame.DockedWidgets.Tabs]]
TabLabel = "Memory"
TabWidth = 96.80864
TabIsPinned = false
Type = "MemoryPanel"
AutoResize = "Auto_Mul8"
RequestedWidth = 300.0

[[MainDockingFrame.DockedWidgets.Tabs]]
TabLabel = "Watch"
TabWidth = 86.17031
TabIsPinned = false
Type = "WatchPanel"
Columns = [{Width = 160.0}, {Width = 388.0}, {Width = 160.0}]

[[MainDockingFrame.DockedWidgets.Tabs.Items]]
EvalStr = "lines"

[[MainDockingFrame.DockedWidgets.Tabs.Items]]
EvalStr = ""

[[MainDockingFrame.DockedWidgets.Tabs]]
TabLabel = "Auto Watches"
TabWidth = 128.7236
TabIsPinned = false
Type = "AutoWatchPanel"
Columns = [{Width = 160.0}, {Width = 160.0}, {Width = 160.0}]

[[MainDockingFrame.DockedWidgets.Tabs]]
TabLabel = "Find Results"
TabWidth = 117.0215
TabIsPinned = false
Type = "FindResultsPanel"

[[MainDockingFrame.DockedWidgets.Tabs]]
TabLabel = "Console"
TabWidth = 94.68098
TabIsPinned = false
Type = "ConsolePanel"

[[Breakpoints]]
File = "src\\SceneNetworking.bf"
Line = 30
Column = 2

[[BookmarkFolders]]
Title = ""

[OutputFilters]
ModuleLoadMessages = false
ModuleUnloadMessages = false
ProcessExitMessages = false
ThreadCreateMessages = false
ThreadExitMessages = false
SymbolLoadMessages = false
ProgramOutput = false
